modLoader="javafml"
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId="arcraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Arcraft" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="arcraft.png" #optional
credits="Thanks for playing" #optional
authors="ivan.logon01@gmail.com" #optional
description='''

...

'''
[[dependencies.arcraft]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.arcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
